/* eslint-disable */

// @ts-nocheck

// This file was automatically generated by @caffeinelabs/bindgen@0.1.0.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { IDL } from '@icp-sdk/core/candid';

export const UserRole = IDL.Variant({
  'admin' : IDL.Null,
  'user' : IDL.Null,
  'guest' : IDL.Null,
});
export const Item = IDL.Record({ 'productId' : IDL.Nat, 'quantity' : IDL.Nat });
export const CreateOrderInput = IDL.Record({
  'customerName' : IDL.Text,
  'total' : IDL.Nat,
  'address' : IDL.Text,
  'phone' : IDL.Text,
  'items' : IDL.Vec(Item),
});
export const Status = IDL.Variant({
  'shipped' : IDL.Null,
  'pending' : IDL.Null,
  'delivered' : IDL.Null,
  'processing' : IDL.Null,
});
export const Time = IDL.Int;
export const Order = IDL.Record({
  'id' : IDL.Nat,
  'customerName' : IDL.Text,
  'status' : Status,
  'total' : IDL.Nat,
  'createdAt' : Time,
  'address' : IDL.Text,
  'phone' : IDL.Text,
  'items' : IDL.Vec(Item),
});
export const Series = IDL.Variant({
  'naruto' : IDL.Null,
  'pokemon' : IDL.Null,
});
export const Product = IDL.Record({
  'id' : IDL.Nat,
  'name' : IDL.Text,
  'description' : IDL.Text,
  'series' : Series,
  'imageUrl' : IDL.Text,
  'price' : IDL.Nat,
});

export const idlService = IDL.Service({
  '_initializeAccessControlWithSecret' : IDL.Func([IDL.Text], [], []),
  'assignCallerUserRole' : IDL.Func([IDL.Principal, UserRole], [], []),
  'createOrder' : IDL.Func([CreateOrderInput], [IDL.Nat], []),
  'getCallerUserRole' : IDL.Func([], [UserRole], ['query']),
  'getOrders' : IDL.Func([], [IDL.Vec(Order)], ['query']),
  'getProduct' : IDL.Func([IDL.Nat], [Product], ['query']),
  'getProducts' : IDL.Func([], [IDL.Vec(Product)], ['query']),
  'getSeriesText' : IDL.Func([Series], [IDL.Text], ['query']),
  'initialize' : IDL.Func([], [], []),
  'isCallerAdmin' : IDL.Func([], [IDL.Bool], ['query']),
  'updateOrderStatus' : IDL.Func([IDL.Nat, Status], [], []),
});

export const idlInitArgs = [];

export const idlFactory = ({ IDL }) => {
  const UserRole = IDL.Variant({
    'admin' : IDL.Null,
    'user' : IDL.Null,
    'guest' : IDL.Null,
  });
  const Item = IDL.Record({ 'productId' : IDL.Nat, 'quantity' : IDL.Nat });
  const CreateOrderInput = IDL.Record({
    'customerName' : IDL.Text,
    'total' : IDL.Nat,
    'address' : IDL.Text,
    'phone' : IDL.Text,
    'items' : IDL.Vec(Item),
  });
  const Status = IDL.Variant({
    'shipped' : IDL.Null,
    'pending' : IDL.Null,
    'delivered' : IDL.Null,
    'processing' : IDL.Null,
  });
  const Time = IDL.Int;
  const Order = IDL.Record({
    'id' : IDL.Nat,
    'customerName' : IDL.Text,
    'status' : Status,
    'total' : IDL.Nat,
    'createdAt' : Time,
    'address' : IDL.Text,
    'phone' : IDL.Text,
    'items' : IDL.Vec(Item),
  });
  const Series = IDL.Variant({ 'naruto' : IDL.Null, 'pokemon' : IDL.Null });
  const Product = IDL.Record({
    'id' : IDL.Nat,
    'name' : IDL.Text,
    'description' : IDL.Text,
    'series' : Series,
    'imageUrl' : IDL.Text,
    'price' : IDL.Nat,
  });
  
  return IDL.Service({
    '_initializeAccessControlWithSecret' : IDL.Func([IDL.Text], [], []),
    'assignCallerUserRole' : IDL.Func([IDL.Principal, UserRole], [], []),
    'createOrder' : IDL.Func([CreateOrderInput], [IDL.Nat], []),
    'getCallerUserRole' : IDL.Func([], [UserRole], ['query']),
    'getOrders' : IDL.Func([], [IDL.Vec(Order)], ['query']),
    'getProduct' : IDL.Func([IDL.Nat], [Product], ['query']),
    'getProducts' : IDL.Func([], [IDL.Vec(Product)], ['query']),
    'getSeriesText' : IDL.Func([Series], [IDL.Text], ['query']),
    'initialize' : IDL.Func([], [], []),
    'isCallerAdmin' : IDL.Func([], [IDL.Bool], ['query']),
    'updateOrderStatus' : IDL.Func([IDL.Nat, Status], [], []),
  });
};

export const init = ({ IDL }) => { return []; };